DROP TABLE IF EXISTS rel_ent_gr CASCADE;
DROP TABLE IF EXISTS rel_br_gr CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS entertainments CASCADE;
DROP TABLE IF EXISTS brands CASCADE;